# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 11:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2017, 5, 28, 11, 37, 44, 191291, tzinfo=utc))),
                ('date_modified', models.DateTimeField(default=datetime.datetime(2017, 5, 28, 11, 37, 44, 191336, tzinfo=utc))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2017, 5, 28, 11, 37, 44, 192031, tzinfo=utc))),
                ('date_modified', models.DateTimeField(default=datetime.datetime(2017, 5, 28, 11, 37, 44, 192060, tzinfo=utc))),
                ('Bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonnevie_api.BucketList')),
            ],
        ),
    ]
